openapi: 3.2.0
info:
  title: 주거 생활 Apartment API
  version: '1.0'
servers:
- url: https://apis.openapi.sk.com/puzzle/residence
security:
- sec0: []
tags:
- name: Apartment
paths:
  /meta/apts:
    get:
      tags:
      - Apartment
      summary: 데이터 제공 가능 아파트
      description: '* 주거 생활 데이터를 제공하는 아파트의 코드와 아파트명을 조회합니다.

        '
      operationId: apts
      parameters:
      - $ref: '#/components/parameters/ContentTypeJson'
      - $ref: '#/components/parameters/AppKey'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  contents:
                    type: array
                    items:
                      $ref: '#/components/schemas/Apt'
              examples:
                Result:
                  value: "{\n  \"status\": {\n    \"code\": \"00\",\n    \"message\": \"success\",\n    \"totalCount\": 1\n  },\n  \"contents\": [\n    {\n      \"kaptCode\": \"A10024502\",\n      \"kaptName\": \"신대증흥S클래스10단지아파트\"\n    }\n  ]\n}"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
              examples:
                InvalidParameter:
                  value:
                    error:
                      code: '400'
                      message: INVALID_PARAMETER_NAME
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      id:
                        type: string
                      category:
                        type: string
                      code:
                        type: string
                      message:
                        type: string
              examples:
                Unauthorized:
                  value:
                    error:
                      id: '401'
                      category: gw
                      code: UNAUTHORIZED
                      message: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/paths/~1meta~1apts/get/responses/401/content/application~1json/schema'
              examples:
                ForbiddenAppKey:
                  value:
                    error:
                      id: '403'
                      category: gw
                      code: INVALID_API_KEY
                      message: Forbidden
                ForbiddenIP:
                  value:
                    error:
                      id: '403'
                      category: gw
                      code: ACCESS_DENIED
                      message: Authorized IP Address only
                ForbiddenURL:
                  value:
                    error:
                      id: '403'
                      category: gw
                      code: MISSING_AUTHENTICATION_TOKEN
                      message: Missing Authentication Token
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/paths/~1meta~1apts/get/responses/400/content/application~1json/schema'
              examples:
                NotFound:
                  value:
                    error:
                      code: '404'
                      message: NOT_FOUND_DATA
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/paths/~1meta~1apts/get/responses/401/content/application~1json/schema'
              examples:
                Throttled:
                  value:
                    error:
                      id: '429'
                      category: gw
                      code: THROTTLED
                      message: Too Many Requests
                QuataExceeded:
                  value:
                    error:
                      id: '429'
                      category: gw
                      code: QUOTA_EXCEEDED
                      message: Limit Exceeded
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1meta~1apts/get/responses/401/content/application~1json/schema'
              examples:
                InternalServerError:
                  value:
                    error:
                      id: '500'
                      category: gw
                      code: API_CONFIGURATION_ERROR
                      message: Internal server error
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/paths/~1meta~1apts/get/responses/401/content/application~1json/schema'
              examples:
                GatewayTimeout:
                  value:
                    error:
                      id: '504'
                      category: gw
                      code: INTEGRATION_FAILURE
                      message: Network error communicating with endpoint
      deprecated: false
components:
  parameters:
    AppKey:
      name: appKey
      in: header
      description: <a href="https://openapi.sk.com/mypage/project/" target="_blank">대시보드>앱</a>>앱키(appKey) 탭에서 조회
      required: true
      schema:
        type: string
    ContentTypeJson:
      name: Content-Type
      description: application/json
      in: header
      required: true
      schema:
        type: string
        default: application/json
  schemas:
    Apt:
      type: object
      properties:
        kaptCode:
          type: string
          description: 아파트 코드(국토부 기준)
        kaptName:
          type: string
          description: 아파트 이름(국토부 기준)
      required:
      - kaptCode
      - kaptName
    ResponseStatus:
      type: object
      description: 응답 상태입니다.
      properties:
        code:
          type: string
          description: '응답 코드입니다.

            00: 성공

            '
        message:
          type: string
          description: '요청(request) 성공 여부 메시지입니다.

            success: 성공.

            '
        totalCount:
          type: integer
          description: 검색 결과 데이터 건수입니다.
  securitySchemes:
    sec0:
      type: apiKey
      in: header
      x-default: e8wHh2tya84M88aReEpXCa5XTQf3xgo01aZG39k5
      name: appkey
x-readme:
  headers: []
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
x-readme-fauxas: true
